import { describe, expect, it } from "vitest";
import type { SchemaDeclaration } from "../src/core/plugin";
import { coreSchema } from "../src/schema/declaration";
import { renderDrizzleSchema } from "../src/schema/render-drizzle";

const pluginSchema: SchemaDeclaration = {
  digestBucket: {
    tableName: "digest_bucket",
    fields: {
      id: { type: "string", required: true },
      userId: { type: "string", required: true },
      notificationId: { type: "string", required: true },
      window: { type: "string", required: true, default: "daily" },
      createdAt: { type: "date", required: true, defaultNow: true },
    },
    primaryKey: ["id"],
    indexes: [{ on: ["userId", "window"], name: "digest_bucket_user_idx" }],
  },
};

describe("renderDrizzleSchema", () => {
  it("renders a plugin table", () => {
    expect(renderDrizzleSchema(pluginSchema)).toBe(
      `// Generated by easy-notify. Do not edit by hand.
import { index, pgTable, text, timestamp } from "drizzle-orm/pg-core";

export const digestBucket = pgTable(
  "digest_bucket",
  {
    id: text("id").primaryKey(),
    userId: text("user_id").notNull(),
    notificationId: text("notification_id").notNull(),
    window: text("window").notNull().default("daily"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("digest_bucket_user_idx").on(table.userId, table.window),
  ],
);
`,
    );
  });

  it("applies the table prefix to tables and index names", () => {
    const output = renderDrizzleSchema(pluginSchema, "app_");
    expect(output).toContain('pgTable(\n  "app_digest_bucket"');
    expect(output).toContain('index("app_digest_bucket_user_idx")');
  });

  it("renders a composite primary key", () => {
    const output = renderDrizzleSchema({
      notificationPreference: coreSchema.notificationPreference,
    });
    expect(output).toContain("primaryKey({ columns: [table.userId, table.type, table.channel] })");
    expect(output).toContain('enabled: boolean("enabled").notNull().default(true)');
  });

  it("imports only the builders it uses", () => {
    const output = renderDrizzleSchema(pluginSchema);
    expect(output).not.toContain("jsonb");
    expect(output).not.toContain("primaryKey,");
  });
});
