import type { FieldDeclaration, SchemaDeclaration, TableDeclaration } from "../core/plugin";
import { toSnakeCase } from "./declaration";

const COLUMN_BUILDER: Record<FieldDeclaration["type"], string> = {
  string: "text",
  number: "integer",
  boolean: "boolean",
  date: "timestamp",
  json: "jsonb",
};

const literal = (value: string | number | boolean) =>
  typeof value === "string" ? JSON.stringify(value) : String(value);

function renderColumn(name: string, field: FieldDeclaration, isSinglePk: boolean): string {
  const builder = COLUMN_BUILDER[field.type];
  const column = toSnakeCase(name);

  let expression =
    field.type === "date"
      ? `${builder}(${JSON.stringify(column)}, { withTimezone: true })`
      : `${builder}(${JSON.stringify(column)})`;

  if (isSinglePk) return `    ${name}: ${expression}.primaryKey(),`;

  if (field.required) expression += ".notNull()";
  if (field.defaultNow) expression += ".defaultNow()";
  else if (field.default !== undefined) expression += `.default(${literal(field.default)})`;

  return `    ${name}: ${expression},`;
}

function renderTable(key: string, table: TableDeclaration, prefix: string): string {
  const compositePk = (table.primaryKey?.length ?? 0) > 1;
  const singlePk = !compositePk ? table.primaryKey?.[0] : undefined;

  const columns = Object.entries(table.fields)
    .map(([name, field]) => renderColumn(name, field, name === singlePk))
    .join("\n");

  const extras: string[] = [];

  for (const declaration of table.indexes ?? []) {
    const builder = declaration.unique ? "uniqueIndex" : "index";
    const name = declaration.name ?? `${table.tableName}_${declaration.on.join("_")}_idx`;
    const columns = declaration.on.map((field) => `table.${field}`).join(", ");
    extras.push(`    ${builder}(${JSON.stringify(prefix + name)}).on(${columns}),`);
  }

  if (compositePk) {
    const columns = (table.primaryKey ?? []).map((field) => `table.${field}`).join(", ");
    extras.push(`    primaryKey({ columns: [${columns}] }),`);
  }

  const third = extras.length ? `,\n  (table) => [\n${extras.join("\n")}\n  ]` : "";

  return `export const ${key} = pgTable(\n  ${JSON.stringify(prefix + table.tableName)},\n  {\n${columns}\n  }${third},\n);`;
}

/** Renders a SchemaDeclaration to Drizzle pg-core source. */
export function renderDrizzleSchema(schema: SchemaDeclaration, prefix = ""): string {
  const tables = Object.entries(schema);

  const used = new Set<string>(["pgTable"]);
  for (const [, table] of tables) {
    for (const field of Object.values(table.fields)) used.add(COLUMN_BUILDER[field.type]);
    for (const declaration of table.indexes ?? []) {
      used.add(declaration.unique ? "uniqueIndex" : "index");
    }
    if ((table.primaryKey?.length ?? 0) > 1) used.add("primaryKey");
  }

  const imports = [...used].sort().join(", ");
  const body = tables.map(([key, table]) => renderTable(key, table, prefix)).join("\n\n");

  return `// Generated by easy-notify. Do not edit by hand.\nimport { ${imports} } from "drizzle-orm/pg-core";\n\n${body}\n`;
}
